# Generated by Django 4.1.5 on 2024-03-23 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dae',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='detail',
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='detail', max_length=23),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.ImageField(default='none', max_length=120, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
