# Generated by Django 4.1.5 on 2024-03-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_dae_data_date_remove_data_detail_data_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='detail',
        ),
    ]
